# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75f19d062504009aa76f722c76f317d6341752334ecfe7b87751aa3f897d1cef97033c49e19fb500be26ac10f7cbdbc27d8ad2d69c9a5f3137455d513b24fcd5

test:
  secret_key_base: f22252dfb9fb527d5e0fd82d4e4e7fb74566f6020d12dfb48592901b0d87ad4300562e70279729092224e5e2feb77c9cb7f5ed1fc7c2ca7749b990ce42917bdd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
